### ISSUE TITLE
MT+Strom 3,5,6

### ISSUE THREAD

**Issue by Shanigen** [draliii/School-notes#2]
Tyhle příklady mají u sebe otazníky, které je potřeba vyřešit.

**Comment by KSonny4** [comment]
Mas tam spatnej vysledek u toho 6. prikladu, ale jak k nemu prisli to netusim.

U te 6. je ten case 2 asi opavdu dobre nooo..
bud mas 
1. n*log(n) nalezi O(n^(1-eps))
2. n*log(n) nalezi THETA(n)
3. n*log(n) nalezi OMEGA(n^(1+eps))

kdyz v 1. dame eps > 1 tak ta fce roste pomaleji jak n*log(n)
kdyz v 3. dame treba eps => 1 tak zas ta fce roste rychleji a nic jsme neomezili..

takze bohuzel zbyva 2...

Sarlatanska kucharka :(

**Comment by Shanigen** [comment]
http://bigocheatsheet.com/ podle tohodle s tebou nesouhlasim.

**Comment by KSonny4** [comment]
no podle tohodle to nespada ani do 1. ani do 3. ...

**Comment by Shanigen** [comment]
Podle tohodle, ale THETA(n) je picovina http://bigocheatsheet.com/

**Comment by Shanigen** [comment]
Prave, proto netusim, jak dospeli ke 2

**Comment by KSonny4** [comment]
imho proto, ze 1. a 3. jsou vetsi picovina... Je to hrozne sarlatanskej predmet.

**Comment by Shanigen** [comment]
Commit #8fee025  by to mel resit.
